// <auto-generated />
using System;
using BibliaOnline.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BibliaOnline.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BibliaOnline.Domain.Entities.BibleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Code")
                        .IsUnique();

                    b.ToTable("bible_versions", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CanonicalNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalNumber")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.BookTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BibleVersionId", "BookId")
                        .IsUnique();

                    b.ToTable("book_titles", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.FavoriteVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BibleVersionId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BibleVersionId", "BookId", "ChapterNumber", "VerseNumber")
                        .IsUnique();

                    b.ToTable("favorite_verses", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("boolean");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.ReadingHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BibleVersionId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BibleVersionId", "BookId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("reading_history", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.Verse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibleVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BibleVersionId", "BookId", "ChapterNumber", "VerseNumber")
                        .IsUnique();

                    b.ToTable("verses", (string)null);
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.BibleVersion", b =>
                {
                    b.HasOne("BibliaOnline.Domain.Entities.Language", "Language")
                        .WithMany("Versions")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.BookTitle", b =>
                {
                    b.HasOne("BibliaOnline.Domain.Entities.BibleVersion", "BibleVersion")
                        .WithMany("BookTitles")
                        .HasForeignKey("BibleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliaOnline.Domain.Entities.Book", "Book")
                        .WithMany("Titles")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleVersion");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.FavoriteVerse", b =>
                {
                    b.HasOne("BibliaOnline.Domain.Entities.BibleVersion", "BibleVersion")
                        .WithMany()
                        .HasForeignKey("BibleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliaOnline.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliaOnline.Domain.Entities.UserAccount", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleVersion");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.ReadingHistoryEntry", b =>
                {
                    b.HasOne("BibliaOnline.Domain.Entities.BibleVersion", "BibleVersion")
                        .WithMany()
                        .HasForeignKey("BibleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliaOnline.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliaOnline.Domain.Entities.UserAccount", "User")
                        .WithMany("ReadingHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleVersion");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.Verse", b =>
                {
                    b.HasOne("BibliaOnline.Domain.Entities.BibleVersion", "BibleVersion")
                        .WithMany("Verses")
                        .HasForeignKey("BibleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliaOnline.Domain.Entities.Book", "Book")
                        .WithMany("Verses")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleVersion");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.BibleVersion", b =>
                {
                    b.Navigation("BookTitles");

                    b.Navigation("Verses");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.Book", b =>
                {
                    b.Navigation("Titles");

                    b.Navigation("Verses");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.Language", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BibliaOnline.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("ReadingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
